import Foundation

/// Single source of truth for currency metadata.
/// Emoji and name are hardcoded here and never fetched from API.
/// Rates are the only dynamic data.
struct CurrencyInfo: Identifiable {
    let code: String
    let name: String
    let emoji: String

    var id: String { code }

    /// Complete catalog of supported currencies.
    /// This is the **only** place where metadata is defined.
    static let catalog: [CurrencyInfo] = [
        CurrencyInfo(code: "AED", name: "United Arab Emirates Dirham", emoji: "🇦🇪"),
        CurrencyInfo(code: "AFN", name: "Afghan Afghani", emoji: "🇦🇫"),
        CurrencyInfo(code: "ALL", name: "Albanian Lek", emoji: "🇦🇱"),
        CurrencyInfo(code: "AMD", name: "Armenian Dram", emoji: "🇦🇲"),
        CurrencyInfo(code: "ANG", name: "Netherlands Antillean Gulden", emoji: "🇨🇼"),
        CurrencyInfo(code: "AOA", name: "Angolan Kwanza", emoji: "🇦🇴"),
        CurrencyInfo(code: "ARS", name: "Argentine Peso", emoji: "🇦🇷"),
        CurrencyInfo(code: "AUD", name: "Australian Dollar", emoji: "🇦🇺"),
        CurrencyInfo(code: "AWG", name: "Aruban Florin", emoji: "🇦🇼"),
        CurrencyInfo(code: "AZN", name: "Azerbaijani Manat", emoji: "🇦🇿"),
        CurrencyInfo(code: "BAM", name: "Bosnia and Herzegovina Convertible Mark", emoji: "🇧🇦"),
        CurrencyInfo(code: "BBD", name: "Barbadian Dollar", emoji: "🇧🇧"),
        CurrencyInfo(code: "BDT", name: "Bangladeshi Taka", emoji: "🇧🇩"),
        CurrencyInfo(code: "BGN", name: "Bulgarian Lev", emoji: "🇧🇬"),
        CurrencyInfo(code: "BHD", name: "Bahraini Dinar", emoji: "🇧🇭"),
        CurrencyInfo(code: "BIF", name: "Burundian Franc", emoji: "🇧🇮"),
        CurrencyInfo(code: "BMD", name: "Bermudian Dollar", emoji: "🇧🇲"),
        CurrencyInfo(code: "BND", name: "Brunei Dollar", emoji: "🇧🇳"),
        CurrencyInfo(code: "BOB", name: "Bolivian Boliviano", emoji: "🇧🇴"),
        CurrencyInfo(code: "BRL", name: "Brazilian Real", emoji: "🇧🇷"),
        CurrencyInfo(code: "BSD", name: "Bahamian Dollar", emoji: "🇧🇸"),
        CurrencyInfo(code: "BTN", name: "Bhutanese Ngultrum", emoji: "🇧🇹"),
        CurrencyInfo(code: "BWP", name: "Botswana Pula", emoji: "🇧🇼"),
        CurrencyInfo(code: "BYN", name: "Belarusian Ruble", emoji: "🇧🇾"),
        CurrencyInfo(code: "BZD", name: "Belize Dollar", emoji: "🇧🇿"),
        CurrencyInfo(code: "CAD", name: "Canadian Dollar", emoji: "🇨🇦"),
        CurrencyInfo(code: "CDF", name: "Congolese Franc", emoji: "🇨🇩"),
        CurrencyInfo(code: "CHF", name: "Swiss Franc", emoji: "🇨🇭"),
        CurrencyInfo(code: "CLP", name: "Chilean Peso", emoji: "🇨🇱"),
        CurrencyInfo(code: "CNH", name: "Chinese Renminbi Yuan Offshore", emoji: "🇨🇳"),
        CurrencyInfo(code: "CNY", name: "Chinese Renminbi Yuan", emoji: "🇨🇳"),
        CurrencyInfo(code: "COP", name: "Colombian Peso", emoji: "🇨🇴"),
        CurrencyInfo(code: "CRC", name: "Costa Rican Colón", emoji: "🇨🇷"),
        CurrencyInfo(code: "CUP", name: "Cuban Peso", emoji: "🇨🇺"),
        CurrencyInfo(code: "CVE", name: "Cape Verdean Escudo", emoji: "🇨🇻"),
        CurrencyInfo(code: "CZK", name: "Czech Koruna", emoji: "🇨🇿"),
        CurrencyInfo(code: "DJF", name: "Djiboutian Franc", emoji: "🇩🇯"),
        CurrencyInfo(code: "DKK", name: "Danish Krone", emoji: "🇩🇰"),
        CurrencyInfo(code: "DOP", name: "Dominican Peso", emoji: "🇩🇴"),
        CurrencyInfo(code: "DZD", name: "Algerian Dinar", emoji: "🇩🇿"),
        CurrencyInfo(code: "EGP", name: "Egyptian Pound", emoji: "🇪🇬"),
        CurrencyInfo(code: "ERN", name: "Eritrean Nakfa", emoji: "🇪🇷"),
        CurrencyInfo(code: "ETB", name: "Ethiopian Birr", emoji: "🇪🇹"),
        CurrencyInfo(code: "EUR", name: "Euro", emoji: "🇪🇺"),
        CurrencyInfo(code: "FJD", name: "Fijian Dollar", emoji: "🇫🇯"),
        CurrencyInfo(code: "FKP", name: "Falkland Pound", emoji: "🇫🇰"),
        CurrencyInfo(code: "GBP", name: "British Pound", emoji: "🇬🇧"),
        CurrencyInfo(code: "GEL", name: "Georgian Lari", emoji: "🇬🇪"),
        CurrencyInfo(code: "GGP", name: "Guernsey Pound", emoji: "🇬🇬"),
        CurrencyInfo(code: "GHS", name: "Ghanaian Cedi", emoji: "🇬🇭"),
        CurrencyInfo(code: "GIP", name: "Gibraltar Pound", emoji: "🇬🇮"),
        CurrencyInfo(code: "GMD", name: "Gambian Dalasi", emoji: "🇬🇲"),
        CurrencyInfo(code: "GNF", name: "Guinean Franc", emoji: "🇬🇳"),
        CurrencyInfo(code: "GTQ", name: "Guatemalan Quetzal", emoji: "🇬🇹"),
        CurrencyInfo(code: "GYD", name: "Guyanese Dollar", emoji: "🇬🇾"),
        CurrencyInfo(code: "HKD", name: "Hong Kong Dollar", emoji: "🇭🇰"),
        CurrencyInfo(code: "HNL", name: "Honduran Lempira", emoji: "🇭🇳"),
        CurrencyInfo(code: "HTG", name: "Haitian Gourde", emoji: "🇭🇹"),
        CurrencyInfo(code: "HUF", name: "Hungarian Forint", emoji: "🇭🇺"),
        CurrencyInfo(code: "IDR", name: "Indonesian Rupiah", emoji: "🇮🇩"),
        CurrencyInfo(code: "ILS", name: "Israeli New Shekel", emoji: "🇮🇱"),
        CurrencyInfo(code: "IMP", name: "Isle of Man Pound", emoji: "🇮🇲"),
        CurrencyInfo(code: "INR", name: "Indian Rupee", emoji: "🇮🇳"),
        CurrencyInfo(code: "IQD", name: "Iraqi Dinar", emoji: "🇮🇶"),
        CurrencyInfo(code: "IRR", name: "Iranian Rial", emoji: "🇮🇷"),
        CurrencyInfo(code: "ISK", name: "Icelandic Króna", emoji: "🇮🇸"),
        CurrencyInfo(code: "JEP", name: "Jersey Pound", emoji: "🇯🇪"),
        CurrencyInfo(code: "JMD", name: "Jamaican Dollar", emoji: "🇯🇲"),
        CurrencyInfo(code: "JOD", name: "Jordanian Dinar", emoji: "🇯🇴"),
        CurrencyInfo(code: "JPY", name: "Japanese Yen", emoji: "🇯🇵"),
        CurrencyInfo(code: "KES", name: "Kenyan Shilling", emoji: "🇰🇪"),
        CurrencyInfo(code: "KGS", name: "Kyrgyzstani Som", emoji: "🇰🇬"),
        CurrencyInfo(code: "KHR", name: "Cambodian Riel", emoji: "🇰🇭"),
        CurrencyInfo(code: "KMF", name: "Comorian Franc", emoji: "🇰🇲"),
        CurrencyInfo(code: "KRW", name: "South Korean Won", emoji: "🇰🇷"),
        CurrencyInfo(code: "KWD", name: "Kuwaiti Dinar", emoji: "🇰🇼"),
        CurrencyInfo(code: "KYD", name: "Cayman Islands Dollar", emoji: "🇰🇾"),
        CurrencyInfo(code: "KZT", name: "Kazakhstani Tenge", emoji: "🇰🇿"),
        CurrencyInfo(code: "LAK", name: "Lao Kip", emoji: "🇱🇦"),
        CurrencyInfo(code: "LBP", name: "Lebanese Pound", emoji: "🇱🇧"),
        CurrencyInfo(code: "LKR", name: "Sri Lankan Rupee", emoji: "🇱🇰"),
        CurrencyInfo(code: "LRD", name: "Liberian Dollar", emoji: "🇱🇷"),
        CurrencyInfo(code: "LSL", name: "Lesotho Loti", emoji: "🇱🇸"),
        CurrencyInfo(code: "LYD", name: "Libyan Dinar", emoji: "🇱🇾"),
        CurrencyInfo(code: "MAD", name: "Moroccan Dirham", emoji: "🇲🇦"),
        CurrencyInfo(code: "MDL", name: "Moldovan Leu", emoji: "🇲🇩"),
        CurrencyInfo(code: "MGA", name: "Malagasy Ariary", emoji: "🇲🇬"),
        CurrencyInfo(code: "MKD", name: "Macedonian Denar", emoji: "🇲🇰"),
        CurrencyInfo(code: "MMK", name: "Myanmar Kyat", emoji: "🇲🇲"),
        CurrencyInfo(code: "MNT", name: "Mongolian Tögrög", emoji: "🇲🇳"),
        CurrencyInfo(code: "MOP", name: "Macanese Pataca", emoji: "🇲🇴"),
        CurrencyInfo(code: "MRU", name: "Mauritanian Ouguiya", emoji: "🇲🇷"),
        CurrencyInfo(code: "MUR", name: "Mauritian Rupee", emoji: "🇲🇺"),
        CurrencyInfo(code: "MVR", name: "Maldivian Rufiyaa", emoji: "🇲🇻"),
        CurrencyInfo(code: "MWK", name: "Malawian Kwacha", emoji: "🇲🇼"),
        CurrencyInfo(code: "MXN", name: "Mexican Peso", emoji: "🇲🇽"),
        CurrencyInfo(code: "MYR", name: "Malaysian Ringgit", emoji: "🇲🇾"),
        CurrencyInfo(code: "MZN", name: "Mozambican Metical", emoji: "🇲🇿"),
        CurrencyInfo(code: "NAD", name: "Namibian Dollar", emoji: "🇳🇦"),
        CurrencyInfo(code: "NGN", name: "Nigerian Naira", emoji: "🇳🇬"),
        CurrencyInfo(code: "NIO", name: "Nicaraguan Córdoba", emoji: "🇳🇮"),
        CurrencyInfo(code: "NOK", name: "Norwegian Krone", emoji: "🇳🇴"),
        CurrencyInfo(code: "NPR", name: "Nepalese Rupee", emoji: "🇳🇵"),
        CurrencyInfo(code: "NZD", name: "New Zealand Dollar", emoji: "🇳🇿"),
        CurrencyInfo(code: "OMR", name: "Omani Rial", emoji: "🇴🇲"),
        CurrencyInfo(code: "PAB", name: "Panamanian Balboa", emoji: "🇵🇦"),
        CurrencyInfo(code: "PEN", name: "Peruvian Sol", emoji: "🇵🇪"),
        CurrencyInfo(code: "PGK", name: "Papua New Guinean Kina", emoji: "🇵🇬"),
        CurrencyInfo(code: "PHP", name: "Philippine Peso", emoji: "🇵🇭"),
        CurrencyInfo(code: "PKR", name: "Pakistani Rupee", emoji: "🇵🇰"),
        CurrencyInfo(code: "PLN", name: "Polish Złoty", emoji: "🇵🇱"),
        CurrencyInfo(code: "PYG", name: "Paraguayan Guaraní", emoji: "🇵🇾"),
        CurrencyInfo(code: "QAR", name: "Qatari Riyal", emoji: "🇶🇦"),
        CurrencyInfo(code: "RON", name: "Romanian Leu", emoji: "🇷🇴"),
        CurrencyInfo(code: "RSD", name: "Serbian Dinar", emoji: "🇷🇸"),
        CurrencyInfo(code: "RUB", name: "Russian Ruble", emoji: "🇷🇺"),
        CurrencyInfo(code: "RWF", name: "Rwandan Franc", emoji: "🇷🇼"),
        CurrencyInfo(code: "SAR", name: "Saudi Riyal", emoji: "🇸🇦"),
        CurrencyInfo(code: "SBD", name: "Solomon Islands Dollar", emoji: "🇸🇧"),
        CurrencyInfo(code: "SCR", name: "Seychellois Rupee", emoji: "🇸🇨"),
        CurrencyInfo(code: "SDG", name: "Sudanese Pound", emoji: "🇸🇩"),
        CurrencyInfo(code: "SEK", name: "Swedish Krona", emoji: "🇸🇪"),
        CurrencyInfo(code: "SGD", name: "Singapore Dollar", emoji: "🇸🇬"),
        CurrencyInfo(code: "SHP", name: "Saint Helenian Pound", emoji: "🇸🇭"),
        CurrencyInfo(code: "SLE", name: "New Leone", emoji: "🇸🇱"),
        CurrencyInfo(code: "SOS", name: "Somali Shilling", emoji: "🇸🇴"),
        CurrencyInfo(code: "SRD", name: "Surinamese Dollar", emoji: "🇸🇷"),
        CurrencyInfo(code: "SSP", name: "South Sudanese Pound", emoji: "🇸🇸"),
        CurrencyInfo(code: "STN", name: "São Tomé and Príncipe Dobra", emoji: "🇸🇹"),
        CurrencyInfo(code: "SVC", name: "Salvadoran Colón", emoji: "🇸🇻"),
        CurrencyInfo(code: "SYP", name: "Syrian Pound", emoji: "🇸🇾"),
        CurrencyInfo(code: "SZL", name: "Swazi Lilangeni", emoji: "🇸🇿"),
        CurrencyInfo(code: "THB", name: "Thai Baht", emoji: "🇹🇭"),
        CurrencyInfo(code: "TJS", name: "Tajikistani Somoni", emoji: "🇹🇯"),
        CurrencyInfo(code: "TMT", name: "Turkmenistani Manat", emoji: "🇹🇲"),
        CurrencyInfo(code: "TND", name: "Tunisian Dinar", emoji: "🇹🇳"),
        CurrencyInfo(code: "TOP", name: "Tongan Paʻanga", emoji: "🇹🇴"),
        CurrencyInfo(code: "TRY", name: "Turkish Lira", emoji: "🇹🇷"),
        CurrencyInfo(code: "TTD", name: "Trinidad and Tobago Dollar", emoji: "🇹🇹"),
        CurrencyInfo(code: "TWD", name: "New Taiwan Dollar", emoji: "🇹🇼"),
        CurrencyInfo(code: "TZS", name: "Tanzanian Shilling", emoji: "🇹🇿"),
        CurrencyInfo(code: "UAH", name: "Ukrainian Hryvnia", emoji: "🇺🇦"),
        CurrencyInfo(code: "UGX", name: "Ugandan Shilling", emoji: "🇺🇬"),
        CurrencyInfo(code: "USD", name: "United States Dollar", emoji: "🇺🇸"),
        CurrencyInfo(code: "UYU", name: "Uruguayan Peso", emoji: "🇺🇾"),
        CurrencyInfo(code: "UZS", name: "Uzbekistan Som", emoji: "🇺🇿"),
        CurrencyInfo(code: "VES", name: "Venezuelan Bolívar Soberano", emoji: "🇻🇪"),
        CurrencyInfo(code: "VND", name: "Vietnamese Đồng", emoji: "🇻🇳"),
        CurrencyInfo(code: "VUV", name: "Vanuatu Vatu", emoji: "🇻🇺"),
        CurrencyInfo(code: "WST", name: "Samoan Tala", emoji: "🇼🇸"),
        CurrencyInfo(code: "XAF", name: "Central African CFA Franc", emoji: "🇨🇫"),
        CurrencyInfo(code: "XAG", name: "Silver (Troy Ounce)", emoji: "🪙"),
        CurrencyInfo(code: "XAU", name: "Gold (Troy Ounce)", emoji: "⚱️"),
        CurrencyInfo(code: "XCD", name: "East Caribbean Dollar", emoji: "🌎"),
        CurrencyInfo(code: "XCG", name: "Caribbean Guilder", emoji: "🇨🇼"),
        CurrencyInfo(code: "XOF", name: "West African CFA Franc", emoji: "🌍"),
        CurrencyInfo(code: "XPF", name: "CFP Franc", emoji: "🇵🇫"),
        CurrencyInfo(code: "YER", name: "Yemeni Rial", emoji: "🇾🇪"),
        CurrencyInfo(code: "ZAR", name: "South African Rand", emoji: "🇿🇦"),
        CurrencyInfo(code: "ZMW", name: "Zambian Kwacha", emoji: "🇿🇲"),
        CurrencyInfo(code: "ZWG", name: "Zimbabwe Gold", emoji: "🇿🇼"),
    ]

    /// Fast lookup by code.
    static let byCode: [String: CurrencyInfo] = {
        Dictionary(uniqueKeysWithValues: catalog.map { ($0.code, $0) })
    }()

    /// All known currency codes.
    static let allCodes: Set<String> = {
        Set(catalog.map { $0.code })
    }()
}
